#!/usr/bin/env python

import subprocess
import sys
import time

SLEEP_TIME = 1


def get_frequencies() -> tuple[int, int]:
    process = subprocess.run(
        ["grep", "--color=never", "cpu MHz", "/proc/cpuinfo"], capture_output=True
    )
    lines = process.stdout.decode("utf8").strip().splitlines()
    freq_strs = (line.split()[-1] for line in lines)
    frequencies = [int(s.split(".")[0]) for s in freq_strs]
    return max(frequencies), min(frequencies)


def format_frequency(frequency: int) -> str:
    if frequency >= 1000:
        freq_float = frequency / 1000
        return f"{freq_float:1.1f}GHz"
    else:
        return f"{frequency:>3}MHz"


def main() -> None:
    while True:
        frequencies = get_frequencies()
        out = " ".join(format_frequency(frequency) for frequency in frequencies)
        sys.stdout.write(out)
        sys.stdout.write("\n")
        sys.stdout.flush()
        time.sleep(SLEEP_TIME)


if __name__ == "__main__":
    main()
