#!/usr/bin/env python

import json
import os

from datetime import datetime
from threading import Timer
from time import time


def print_time():
    t = Timer(1.0, print_time).start()
    print(datetime.now().isoformat())


timer = Timer(1.0, print_time)

while time() % 1 > 0.001:
    pass

print_time()
