#!/usr/bin/env bash

# to be run as a cron job every minute by root

STATUS_FILE=/tmp/disk_status
STANDBY_MINUTES=11

print_new_status () {
    if smartctl -i -n standby "/dev/$1" &> /dev/null; then
	printf "%s %s %d\n" $1 UP     ${STANDBY_MINUTES}
    else
	printf "%s %s %d\n" $1 ASLEEP 0
    fi
}

if [ -s ${STATUS_FILE} ]; then
    mv ${STATUS_FILE} ${STATUS_FILE}.old
    while read disk status timeout; do
	if [ ${timeout} = 0 ]; then
	    print_new_status ${disk}
	else
	    printf "%s %s %d\n" ${disk} ${status} $((timeout-1))
	fi
    done < ${STATUS_FILE}.old > ${STATUS_FILE}
    rm ${STATUS_FILE}.old
else
    disks=("sda" "sdb" "sdc" "sdd" "sde")

    for disk in ${disks[@]}; do
	print_new_status ${disk}
    done > ${STATUS_FILE}
fi

pkill --signal RTMIN+3 i3blocks
