#!/usr/bin/env python

import os
import sys
from pathlib import Path
from subprocess import run, PIPE

git_icon = "󰊢"
branch_icon = ""

green = "#7F9F7F"
yellow = "#F0DFAF"
red = "#CC9393"

git_repo = Path(os.environ["GIT_REPO"]).expanduser()
git_upstream = os.environ.get("GIT_UPSTREAM")


def out_with_colour(string, colour=None) -> None:
    out = with_colour(string, colour)
    sys.stdout.write(out)
    sys.stdout.write("\n")
    sys.stdout.flush()


def with_colour(string, colour=None):
    """Returns string with pango colour"""
    if colour:
        return f'<span foreground="{colour}">{string}</span>'
    return string


def run_git(*cmds: str) -> str:
    proc = run(["git", *cmds], stdout=PIPE, cwd=git_repo)
    return proc.stdout.decode().strip()


def main():
    run_git("fetch")
    git_branch = run_git("branch", "--show-current")

    # working dir status
    git_status = run_git("status", "--porcelain", "--ignore-submodules")

    # unpulled
    git_unpulled = run_git("log", "--oneline", f"HEAD..{git_upstream}")

    # unpushed
    git_unpushed = run_git("log", "--oneline", f"{git_upstream}..HEAD")

    if git_unpulled:
        status = "pull"
        colour = red
    elif git_status:
        status = "dirty"
        colour = yellow
    elif git_unpushed:
        status = "push"
        colour = yellow
    else:
        status = "clean"
        colour = green

    out_with_colour(
        f"{git_icon} {git_repo.name} {branch_icon} {git_branch}",
        colour=colour,
    )
    print(status, file=sys.stderr)


if __name__ == '__main__':
    main()
